remote_theme: pmarsceill/just-the-docs
title: TAR Tutorial at ICAIL 2025
description: Official website for the TAR Tutorial at ICAIL 2025
search_enabled: false
google_analytics: G-413318Y06P
ga_tracking: G-413318Y06P